import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'ress';
import "../styles/globals.scss";
import Header from "@/components/header";
import Mainheader from "@/components/main_header";
import Footer from "@/components/footer";
import AddGroup from "@/components/addGroup";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "illuMe",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header>
          <Mainheader />
        </Header>
        {children}
        <AddGroup />
        <Footer />
      </body>
    </html>
  );
}
